# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import torrent_parser_pb2 as torrent__parser__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in torrent_parser_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TorrentParserStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ParseTitles = channel.stream_stream(
                '/torrentparser.TorrentParser/ParseTitles',
                request_serializer=torrent__parser__pb2.TorrentTitleRequest.SerializeToString,
                response_deserializer=torrent__parser__pb2.TorrentTitleResponse.FromString,
                _registered_method=True)
        self.Shutdown = channel.unary_unary(
                '/torrentparser.TorrentParser/Shutdown',
                request_serializer=torrent__parser__pb2.ShutdownRequest.SerializeToString,
                response_deserializer=torrent__parser__pb2.ShutdownResponse.FromString,
                _registered_method=True)


class TorrentParserServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ParseTitles(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Shutdown(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TorrentParserServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ParseTitles': grpc.stream_stream_rpc_method_handler(
                    servicer.ParseTitles,
                    request_deserializer=torrent__parser__pb2.TorrentTitleRequest.FromString,
                    response_serializer=torrent__parser__pb2.TorrentTitleResponse.SerializeToString,
            ),
            'Shutdown': grpc.unary_unary_rpc_method_handler(
                    servicer.Shutdown,
                    request_deserializer=torrent__parser__pb2.ShutdownRequest.FromString,
                    response_serializer=torrent__parser__pb2.ShutdownResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'torrentparser.TorrentParser', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('torrentparser.TorrentParser', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TorrentParser(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ParseTitles(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/torrentparser.TorrentParser/ParseTitles',
            torrent__parser__pb2.TorrentTitleRequest.SerializeToString,
            torrent__parser__pb2.TorrentTitleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Shutdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/torrentparser.TorrentParser/Shutdown',
            torrent__parser__pb2.ShutdownRequest.SerializeToString,
            torrent__parser__pb2.ShutdownResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
