use parsett_rust::{parse_title, types::Language};

#[test]
fn test_languages_detection() {
    let test_cases = vec![
        ("Deadpool 2016 1080p BluRay DTS Rus Ukr 3xEng HDCL", vec![Language::Russian, Language::Ukrainian]),
        ("VAIANA: MOANA (2017) NL-Retail [2D] EAGLE", vec![Language::Dutch]),
        ("De Noodcentrale S02E05 FLEMISH 540p WEBRip AAC H 264", vec![Language::Dutch]),
        ("The Intern 2015 TRUEFRENCH 720p BluRay x264-PiNKPANTERS", vec![Language::French]),
        ("After Earth 2013 VFF BDrip x264 YJ", vec![Language::French]),
        ("127.Heures.FRENCH.DVDRip.AC3.XViD-DVDFR", vec![Language::French]),
        ("Color.Of.Night.Unrated.DC.VostFR.BRrip.x264", vec![Language::French]),
        ("Le Labyrinthe 2014 Multi-VF2 1080p BluRay x264-PopHD", vec![Language::French]),
        ("Maman, j'ai raté l'avion 1990 VFI 1080p BluRay DTS x265-HTG", vec![Language::French]),
        ("South.Park.S21E10.iTALiAN.FiNAL.AHDTV.x264-NTROPiC", vec![Language::Italian]),
        ("2- English- {SDH}.srt", vec![Language::English]),
        ("1_ English-Subs.srt", vec![Language::English]),
        ("House S 1 CD 1-6 svensk, danska, norsk, finsk sub", vec![Language::Danish, Language::Finnish, Language::Swedish, Language::Norwegian]),
        ("Svein.Og.Rotta.NORSK.Nordic.Subs.2006", vec![Language::Danish, Language::Finnish, Language::Swedish, Language::Norwegian]),
        ("Borat med Norsk Undertekst", vec![Language::Norwegian]),
        ("Subs/21_Bokmal.srt", vec![Language::Norwegian]),
        ("Subs/nob.srt", vec![Language::Norwegian]),
        ("Subs/5_nor.srt", vec![Language::Norwegian]),
        ("Curious.George.2.Follow.That.Monkey.2009.DK.SWE.UK.PAL.DVDR-CATC", vec![Language::Danish, Language::Swedish]),
        ("Yes.Man.Dk-Subs.2009.dingel", vec![Language::Danish]),
        ("Dan-SDH.srt", vec![Language::Danish]),
        ("dan.srt", vec![Language::Danish]),
        ("Red Riding 1974 [2009 PAL DVD][En Subs[Sv.No.Fi]", vec![Language::English, Language::Finnish, Language::Swedish]),
        ("Comme une Image (Look at Me) [2004 PAL DVD][Fr Subs[Sv.Da.No]", vec![Language::French, Language::Swedish]),
        ("A.Good.Day.To.Die.Hard.2013.SWESUB.DANSUB.FiNSUB.720p.WEB-DL.-Ro", vec![Language::Danish, Language::Finnish, Language::Swedish]),
        ("The.Prisoner.1967-1968.Complete.Series.Subs.English+Nordic", vec![Language::English, Language::Danish, Language::Finnish, Language::Swedish, Language::Norwegian]),
        ("Royal.Pains.S05E02.HDTV.subtitulado.esp.sc.avi", vec![Language::Spanish]),
        ("Desmembrados (2006) [HDrip-XviD-AC3][Castellano]", vec![Language::Spanish]),
        ("10_Spanish-Subs.srt", vec![Language::Spanish]),
        ("Patriot Games [1992] Eng, Ger, Cze, Hun, Pol + multisub  DVDrip", vec![Language::English, Language::German, Language::Polish, Language::Czech, Language::Hungarian]),
        ("Elvis Presley - La via del Male (King creole) - IT EN FR DE ES", vec![Language::English, Language::French, Language::Spanish, Language::Italian, Language::German]),
        ("FernGully [H264 - Ita Dut Fre Ger Eng Spa Aac - MultiSub]", vec![Language::English, Language::French, Language::Spanish, Language::Italian, Language::German, Language::Dutch]),
        ("Jesus de Montreal / Jesus of Montreal - subtitulos espanol", vec![Language::Spanish]),
        ("Los.Vengadores.DVDR español ingles clon", vec![Language::English, Language::Spanish]),
        ("EMPIRE STATE 2013 DVDRip TRNC English and Española Latin", vec![Language::English, Language::LatinAmericanSpanish, Language::Spanish]),
        ("Mary Poppins Returns 2019 DVDRip LATINO-1XBET", vec![Language::LatinAmericanSpanish]),
        ("Los Simpsons S18 E01 Latino", vec![Language::LatinAmericanSpanish]),
        ("Spider-Man (2002) Blu-Ray [720p] Dual Ingles-Español", vec![Language::English, Language::Spanish]),
        ("Abuela (2015) 1080p BluRay x264 AC3 Dual Latino-Inglés", vec![Language::English, Language::LatinAmericanSpanish]),
        ("Dumbo.2019.1080p.Dual.Lat", vec![Language::LatinAmericanSpanish]),
        ("A.Score.to.Settle.2019.lati.mp4", vec![Language::LatinAmericanSpanish]),
        ("[S0.E04] Gambit królowej - Gra środkowa.Spanish Latin America.srt", vec![Language::LatinAmericanSpanish]),
        ("Latin American.spa.srt", vec![Language::LatinAmericanSpanish]),
        ("Men in Black International 2019 (inglês português)", vec![Language::English, Language::Portuguese]),
        ("Assassins (1995) Sylvester Stallone.DVDrip.XviD - Italian Englis", vec![Language::English, Language::Italian]),
        ("El Club de la Lucha[dvdrip][spanish]", vec![Language::Spanish]),
        ("The Curse Of The Weeping Woman 2019 BluRay 1080p Tel+Tam+hin+eng", vec![Language::English, Language::Hindi, Language::Telugu, Language::Tamil]),
        ("Inception 2010 1080p BRRIP[dual-audio][eng-hindi]", vec![Language::English, Language::Hindi]),
        ("Inception (2010) 720p BDRip Tamil+Telugu+Hindi+Eng", vec![Language::English, Language::Hindi, Language::Telugu, Language::Tamil]),
        ("Subs/Dear.S01E02.WEBRip.x265-ION265/34_tam.srt", vec![Language::Tamil]),
        ("Subs/Dear.S01E02.WEBRip.x265-ION265/35_tel.srt", vec![Language::Telugu]),
        ("Dabangg 3 2019 AMZN WebRip Hindi 720p x264", vec![Language::Hindi]),
        ("Quarantine [2008] [DVDRiP.XviD-M14CH0] [Lektor PL] [Arx]", vec![Language::Polish]),
        ("The Mandalorian S01E06 POLISH WEBRip x264-FLAME", vec![Language::Polish]),
        ("Carros 2 Dublado - Portugues BR (2011)", vec![Language::Portuguese]),
        ("A.Simple.Plan.1998.720p.BDRIP.X264.dublado.portugues.BR.gmenezes", vec![Language::Portuguese]),
        ("American.Horror.Story.S01E01.720p. PORTUGUÊS BR", vec![Language::Portuguese]),
        ("Angel.S05E19.legendado.br.rmvb", vec![Language::Portuguese]),
        ("Grimm S01E11 Dublado BR [ kickUploader ]", vec![Language::Portuguese]),
        ("InuYasha.EP161.ptBR.subtitles.[inuplace.com.br].avi", vec![Language::Portuguese]),
        ("Ghost.Rider.DivX_Gamonet(Ingles-Port.BR)-AC3.avi", vec![Language::English, Language::Portuguese]),
        ("I Am David  legendado pt/br", vec![Language::Portuguese]),
        ("Lone Wolf and Cub 6 movies - legendas BR", vec![Language::Portuguese]),
        ("Wonder Woman Season 3 (H.264 1080p; English/Portuguese-BR)", vec![Language::English, Language::Portuguese]),
        ("MIB 3 - Homens de Preto 2012 ( Audio EN-BR - Leg BR  Mkv 1280x69", vec![Language::English, Language::Portuguese]),
        ("my wife is a gangster 3 legendado em PT(BR)", vec![Language::Portuguese]),
        ("A.Clockwork.Orange.1971.BRDRIP.1080p.DUAL.PORT-BR.ENG.gmenezes.m", vec![Language::English, Language::Portuguese]),
        ("Superman I - O Filme 1978 Leg. BR - Mkv 1280x528", vec![Language::Portuguese]),
        ("Subs/Brazilian.por.srt", vec![Language::Portuguese]),
        ("Brazilian Portuguese.por.srt", vec![Language::Portuguese]),
        ("[S0.E07] Gambit królowej - Gra końcowa.Portuguese Brazil.srt", vec![Language::Portuguese]),
        ("The Hit List (2011) DVD NTSC WS (eng-fre-pt-spa) [Sk]", vec![Language::English, Language::French, Language::Spanish]),
        ("[POPAS] Neon Genesis Evangelion: The End of Evangelion [jp_PT-pt", vec![Language::Japanese, Language::Portuguese]),
        ("Zola Maseko - Drum (2004) PT subs", vec![Language::Portuguese]),
        ("Idrissa Ouedraogo - Yaaba (1989) EN ES FR PT", vec![Language::English, Language::French, Language::Spanish]),
        ("Metallica.Through.The.Never.2013 O Filme(leg.pt-pt)", vec![Language::Portuguese]),
        ("Dinossauro (2000) --[ Ing / Pt / Esp ]", vec![Language::English, Language::Spanish]),
        ("The Guard 2011.DK.EN.ES.HR.NL.PT.RO.Subtitles", vec![Language::English, Language::Spanish, Language::Romanian, Language::Croatian, Language::Dutch, Language::Danish]),
        ("Titan.A.E.2000 720p  HDTV DTS Eng Fra Hun Rom Rus multisub", vec![Language::English, Language::French, Language::Russian, Language::Hungarian, Language::Romanian]),
        ("Frieren - Beyond Journey's End - S01E01 - TBA WEBDL-1080p.Latin American es.ass", vec![Language::LatinAmericanSpanish]),
        ("Frieren - Beyond Journey's End - S01E01 - TBA WEBDL-1080p.Brazilian pt.ass", vec![Language::Portuguese]),
        ("Frieren - Beyond Journey's End - S01E01 - TBA WEBDL-1080p.pt.ass", vec![Language::Portuguese]),
        ("Frieren - Beyond Journey's End - S01E01 - TBA WEBDL-1080p.es.ass", vec![Language::Spanish]),
        ("Frieren - Beyond Journey's End - S01E01 - TBA WEBDL-1080p.de.ass", vec![Language::German]),
        ("Frieren - Beyond Journey's End - S01E01 - TBA WEBDL-1080p.it.ass", vec![Language::Italian]),
        ("Frieren - Beyond Journey's End - S01E01 - TBA WEBDL-1080p.ar.ass", vec![Language::Arabic]),
        ("Subs(ara,fre,ger).srt", vec![Language::French, Language::German, Language::Arabic]),
        ("Subs(chi,eng,ind,kor,may,tha,vie).srt", vec![Language::English, Language::Korean, Language::Chinese, Language::Vietnamese, Language::Indonesian, Language::Thai, Language::Malay]),
        ("Miami.Bici.2020.1080p.NETFLIX.WEB-DL.DDP5.1.H.264.EN-ROSub-ExtremlymTorrents", vec![Language::English, Language::Romanian]),
        ("26_Romanian.srt", vec![Language::Romanian]),
        ("4_Bulgarian.srt", vec![Language::Bulgarian]),
        ("18_srp.srt", vec![Language::Serbian]),
        ("Aranyelet.S01.HUNGARIAN.1080p.WEBRip.DDP5.1.x264-SbR[rartv]", vec![Language::Hungarian]),
        ("Ponyo[2008]DvDrip-H264 Quad Audio[Eng Jap Fre Spa]AC3 5.1[DXO]", vec![Language::English, Language::Japanese, Language::French, Language::Spanish]),
        ("The Mechanic [1972] Eng,Deu,Fra,Esp,Rus + multisub DVDrip", vec![Language::English, Language::French, Language::Spanish, Language::German, Language::Russian]),
        ("Mommie Dearest [1981 PAL DVD][En.De.Fr.It.Es Multisubs[18]", vec![Language::English, Language::French, Language::Spanish, Language::German]),
        ("Pasienio sargyba S01E03 (2016 WEBRip LT)", vec![Language::Lithuanian]),
        ("24_Lithuanian.srt", vec![Language::Lithuanian]),
        ("25_Latvian.srt", vec![Language::Latvian]),
        ("13_Estonian.srt", vec![Language::Estonian]),
        ("Ip.Man.4.The.Finale.2019.CHINESE.1080p.BluRay.x264.TrueHD.7.1.Atmos-HDC", vec![Language::Chinese]),
        ("should parse CHT language", vec![Language::Chinese]),
        ("Inuyasha_TV+Finale+OVA+Film+CD+Manga+Other; dub jpn,chn,eng sub chs (2019-09-21)", vec![Language::English, Language::Japanese, Language::Chinese]),
        ("Initial D Live Action 2005 ENG/CHI", vec![Language::English, Language::Chinese]),
        ("Wolf.Warrior.2015.720p.BluRay.x264.Mandarin.AAC-ETRG", vec![Language::Chinese]),
        ("Traditional Chinese.chi.srt", vec![Language::Chinese]),
        ("Subs/Promare - Chinese (Traditional).ass", vec![Language::Chinese]),
        ("Berserk 01-25 [dual audio JP,EN] MKV", vec![Language::English, Language::Japanese]),
        ("FLCL S05.1080p HMAX WEB-DL DD2.0 H 264-VARYG (FLCL: Shoegaze Dual-Audio Multi-Subs)", vec![]),
        ("Shinjuku Swan 2015 JAP 1080p BluRay x264 DTS-JYK", vec![Language::Japanese]),
        ("Wet.Woman.in.the.Wind.2016.JAPANESE.1080p.BluRay.x264-iKiW", vec![Language::Japanese]),
        ("All.Love.E146.KOR.HDTV.XViD-DeBTV", vec![Language::Korean]),
        ("The.Nun.2018.KORSUB.HDRip.XviD.MP3-STUTTERSHIT", vec![Language::Korean]),
        ("Burning.2018.KOREAN.720p.BluRay.H264.AAC-VXT", vec![Language::Korean]),
        ("Atonement.2017.KOREAN.ENSUBBED.1080p.WEBRip.x264-VXTT", vec![Language::English, Language::Korean]),
        ("A Freira (2018) Dublado HD-TS 720p", vec![Language::Portuguese]),
        ("Escobar El Patron Del Mal Capitulo 91 SD (2012-10-10) [SiRaDuDe]", vec![Language::Portuguese]),
        ("Bleach - 215 ao 220 - [DB-BR]", vec![Language::Portuguese]),
        ("Joker.2019.MULTi.Bluray.1080p.Atmos.7.1.En.Fr.Sp.Pt-DDR[EtHD]", vec![Language::English, Language::French]),
        ("Dilbert complete series + en subs", vec![Language::English]),
        ("The Next Karate Kid (1994) NTSC WS -Eng/Fre/Spa/Por- [ctang]", vec![Language::English, Language::French, Language::Spanish, Language::Portuguese]),
        ("arsenico por compasion 1944 Capra spanish castellano", vec![Language::Spanish, Language::Portuguese]),
        ("Un.Homme.Et.Une.Femme.1966.DVDRip.XviD.AR [PT ENG ESP]", vec![Language::English, Language::Spanish, Language::Portuguese]),
        ("Geminis.2005.Argentina.ESP.ENG.PT.SUBS", vec![Language::English, Language::Spanish, Language::Portuguese]),
        ("1917 2019 1080p Bluray x264-Sexmeup [Greek Subs] [Braveheart]", vec![Language::Greek]),
        ("The Lion King 1,2,3 Greek Language", vec![Language::Greek]),
        ("The Adams Family (1991) (Greek Subs integratet)", vec![Language::Greek]),
        ("6_Greek.srt", vec![Language::Greek]),
        ("The Insult (2017) [BluRay] [720p] Arabic", vec![Language::Arabic]),
        ("The.Mexican.2001 - Arabic Subs Hardcoded", vec![Language::Arabic]),
        ("Much Loved (2015) - DVDRip x265 HEVC - ARAB-ITA-FRE AUDIO (ENG S", vec![Language::English, Language::French, Language::Italian, Language::Arabic]),
        ("42.2013.720p.BluRay.x264.HD4Ar Arab subtitle", vec![Language::Arabic]),
        ("Fauda.S01.HEBREW.1080p.NF.WEBRip.DD5.1.x264-TrollHD[rartv]", vec![Language::Hebrew]),
        ("madagascar 720p hebrew dubbed.mkv", vec![Language::Hebrew]),
        ("Into.the.Night.S01E04.Ayaz.1080p.NF.WEB-DL.DDP5.1.x264-NTG_track17_[heb].srt", vec![Language::Hebrew]),
        ("The.Protector.2018.S03.TURKISH.WEBRip.x264-ION10", vec![Language::Turkish]),
        ("Recep Ivedik 6 (2020) NETFLIX 720p WEBDL (Turkish) - ExtremlymTorrents", vec![Language::Turkish]),
        ("The Insider*1999*[DVD5][PAL][ENG, POL, sub. ROM, TUR]", vec![Language::English, Language::Polish, Language::Romanian, Language::Turkish]),
        ("Japanese.Story.2003.1080p.WEBRip.x264-RARBG", vec![]),
        ("[ Torrent9.cz ] The.InBetween.S01E10.FiNAL.HDTV.XviD-EXTREME.avi", vec![]),
        ("Thai Massage (2022) 720p PDVDRip x264 AAC.mkv", vec![]),
        ("Carson Daly 2017 09 13 Dan Harmon 720p HDTV x264-CROOKS", vec![]),
        ("Dan Browns The Lost Symbol S01E03 1080p WEB H264-GLHF", vec![]),
        ("Ben.Ara.2015.1080p.WEBRip.x265-RARBG.mp4", vec![]),
        ("Ara.(A.Break).2008.DVDRip", vec![]),
        ("www.1TamilMV.cz - Mirzapur (2020) S02 EP (01-10) - HQ HDRip - [Tam+ Tel] - x264 - AAC - 1GB - ESub", vec![Language::English, Language::Telugu, Language::Tamil]),
        ("www.1TamilMV.cz - The Game of Chathurangam (2023) WEB-DL - 1080p - AVC - (AAC 2.0) [Tamil + Malayalam] - 1.2GB.mkv", vec![Language::Tamil, Language::Malayalam]),
        ("www.1TamilMV.yt - Anchakkallakokkan (2024) Malayalam HQ HDRip - 720p - HEVC - (DD+5.1 - 192Kbps & AAC) - 750MB - ESub.mkv", vec![Language::English, Language::Malayalam]),
        ("Anatomia De Grey - Temporada 19 [HDTV][Cap.1905][Castellano][www.AtomoHD.nu].avi", vec![Language::Spanish]),
        ("Godzilla.x.Kong.The.New.Empire.2024.2160p.BluRay.REMUX.DV.P7.HDR.ENG.LATINO.GER.ITA.FRE.HINDI.CHINESE.TrueHD.Atmos.7.1.H265-BEN.THE.MEN", vec![Language::English, Language::Chinese, Language::French, Language::LatinAmericanSpanish, Language::Italian, Language::German, Language::Hindi]),
        ("Sampurna.2023.Bengali.S02.1080p.AMZN.WEB-DL.DD+2.0.H.265-TheBiscuitMan", vec![Language::Bengali]),
        ("Kingdom.of.the.Planet.of.the.Apes.2024.HDRIP.1080P.[xDark [SaveHD] Latin + English + Hindi.mp4", vec![Language::English, Language::LatinAmericanSpanish, Language::Hindi]),
        ("The Karate Kid Part III 1989 1080p DUAL TİVİBU WEB-DL x264 AAC - HdT", vec![Language::Turkish]),
    ];

    for (input, expected_languages) in test_cases {
        let result = parse_title(input).unwrap();
        assert_eq!(
            result.languages, expected_languages,
            "Incorrect languages detected for {}: Got {:?}, expected {:?}",
            input, result.languages, expected_languages
        );
    }
}
