#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Quality {
    Unknown = 0,
    TeleSync = 1,
    TeleCine = 2,
    SCR = 3,
    BluRay = 4,
    BluRayRemux = 5,
    Remux = 6,
    UHDRip = 7,
    HDRip = 8,
    BRRip = 9,
    BDRip = 10,
    DVDRip = 11,
    VHSRip = 12,
    DVD = 13,
    VHS = 14,
    PPVRip = 15,
    HDTVRip = 16,
    HDTV = 17,
    SATRip = 18,
    TVRip = 19,
    R5 = 20,
    WebMux = 21,
    WebRip = 22,
    WebDL = 23,
    WebDLRip = 24,
    Web = 25,
    Cam = 26,
    PDTV = 27,
}

impl Quality {
    pub fn as_str(&self) -> &'static str {
        match self {
            Quality::Unknown => "unknown",
            Quality::TeleSync => "TeleSync",
            Quality::TeleCine => "TeleCine",
            Quality::SCR => "SCR",
            Quality::BluRay => "BluRay",
            Quality::BluRayRemux => "BluRay REMUX",
            Quality::Remux => "REMUX",
            Quality::UHDRip => "UHDRip",
            Quality::HDRip => "HDRip",
            Quality::BRRip => "BRRip",
            Quality::BDRip => "BDRip",
            Quality::DVDRip => "DVDRip",
            Quality::VHSRip => "VHSRip",
            Quality::DVD => "DVD",
            Quality::VHS => "VHS",
            Quality::PPVRip => "PPVRip",
            Quality::HDTVRip => "HDTVRip",
            Quality::HDTV => "HDTV",
            Quality::SATRip => "SATRip",
            Quality::TVRip => "TVRip",
            Quality::R5 => "R5",
            Quality::WebMux => "WEBMux",
            Quality::WebRip => "WEBRip",
            Quality::WebDL => "WEB-DL",
            Quality::WebDLRip => "WEB-DLRip",
            Quality::Web => "WEB",
            Quality::Cam => "CAM",
            Quality::PDTV => "PDTV",
        }
    }
}
