version: "3"

tasks:
  deps:install:
    desc: Install required Python dependencies using Poetry
    dir: src/PythonPttServer
    cmd: |
      poetry lock
      poetry install --no-root

  deps:remove:
    desc: Remove Poetry virtual environment
    dir: src/PythonPttServer
    cmds:
      - poetry env remove

  proto:generate:
    desc: Generate gRPC stubs for Python
    dir: src/PythonPttServer
    cmds:
      - |
        poetry run python -m grpc_tools.protoc \
          -I {{.PROTO_DIR}} \
          --python_out=. \
          --grpc_python_out=. \
          {{.PROTO_FILE}}
    vars:
      PROTO_DIR: "../Protos"
      PROTO_FILE: "torrent_parser.proto"
    deps: [ deps:install ]