version: "3"

tasks:
  deps:install:
    desc: Install required Go plugins for protoc
    cmds:
      - go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
      - go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest


  deps:remove:
    desc: Remove Go plugins for protoc
    cmds:
      - go clean -i google.golang.org/protobuf/cmd/protoc-gen-go
      - go clean -i google.golang.org/grpc/cmd/protoc-gen-go-grpc

  proto:generate:
    desc: Generate Go code from .proto files
    dir: src/GoPttServer
    cmd: |
      mkdir -p torrentparser || true
      protoc \
        --proto_path="{{.PROTO_DIR}}" \
        --go_out=torrentparser \
        --go_opt=paths=source_relative \
        --go-grpc_out=torrentparser \
        --go-grpc_opt=paths=source_relative \
        "{{.PROTO_DIR}}/{{.PROTO_FILE}}"
    vars:
      PROTO_DIR: "../Protos"
      PROTO_FILE: "torrent_parser.proto"
    deps: [ deps:install ]